--LOST UPDATE
SET TRANSACTION ISOLATION LEVEL Read committed;

SELECT DIACHI FROM KHACHHANG WHERE MAKH = 21;

UPDATE KHACHHANG 
SET DIACHI = N'45 Tân Lập, Đông Hoà, Dĩ An, Bình Dương'
WHERE MAKH = 21;


COMMIT;

SELECT DIACHI FROM KHACHHANG WHERE MAKH = 21;

--------giai quyet -----------
SET TRANSACTION ISOLATION LEVEL serializable;

SELECT DIACHI FROM KHACHHANG WHERE MAKH = 21;

UPDATE KHACHHANG 
SET DIACHI = N'47 Tân Lập, Đông Hoà, Dĩ An, Bình Dương'
WHERE MAKH = 21;


COMMIT;

SELECT DIACHI FROM KHACHHANG WHERE MAKH = 21;


----NON-REPEATABLE READ
SET TRANSACTION ISOLATION LEVEL Read committed;

UPDATE SACH SET GIATIEN = 280000 WHERE MASACH = 3;

COMMIT;

----giai quyet----------
SET TRANSACTION ISOLATION LEVEL serializable;

UPDATE SACH SET GIATIEN = 288000 WHERE MASACH = 3;

COMMIT;


-----PHANTOM READ----
SET TRANSACTION ISOLATION LEVEL serializable;

DELETE FROM KHACHHANG 
WHERE MAKH = 41;

COMMIT;

-----DEADLOCK----
SET TRANSACTION ISOLATION LEVEL Read committed;

UPDATE SACH SET GIATIEN = 160000 WHERE MASACH = 4;

UPDATE SACH SET GIATIEN = 200000 WHERE MASACH = 3;