--LOST UPDATE
SET TRANSACTION ISOLATION LEVEL Read committed;

SELECT DIACHI FROM KHACHHANG WHERE MAKH = 21;

UPDATE KHACHHANG 
SET DIACHI = N'47 Tân Lập, Đông Hoà, Dĩ An, Bình Dương'
WHERE MAKH = 21;


COMMIT;

SELECT DIACHI FROM KHACHHANG WHERE MAKH = 21;

--------giai quyet -----------
SET TRANSACTION ISOLATION LEVEL serializable;

SELECT DIACHI FROM KHACHHANG WHERE MAKH = 21;

UPDATE KHACHHANG 
SET DIACHI = N'43 Tân Lập, Đông Hoà, Dĩ An, Bình Dương'
WHERE MAKH = 21;


COMMIT;

SELECT DIACHI FROM KHACHHANG WHERE MAKH = 21;

----NON-REPEATABLE READ
SET TRANSACTION ISOLATION LEVEL Read committed;

SELECT GIATIEN FROM SACH WHERE MASACH = 3;

SELECT GIATIEN FROM SACH WHERE MASACH = 3;

commit;
----giai quyet----
SET TRANSACTION ISOLATION LEVEL serializable;

SELECT GIATIEN FROM SACH WHERE MASACH = 3;

SELECT GIATIEN FROM SACH WHERE MASACH = 3;

commit;

-----PHANTOM READ----
SET TRANSACTION ISOLATION LEVEL Read committed;

SELECT * FROM KHACHHANG WHERE MAKH = 21;

SELECT * FROM KHACHHANG WHERE MAKH = 21;
COMMIT;

---giai quyet----
SET TRANSACTION ISOLATION LEVEL serializable;

SELECT * FROM KHACHHANG WHERE MAKH = 41;

SELECT * FROM KHACHHANG WHERE MAKH = 41;
COMMIT;


-----DEADLOCK----
SET TRANSACTION ISOLATION LEVEL Read committed;

UPDATE SACH SET GIATIEN = 200000 WHERE MASACH = 3;

UPDATE SACH SET GIATIEN = 160000 WHERE MASACH = 4;